package org.gotson.komga.oracle

import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.MapperFeature
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.SerializationFeature
import org.apache.lucene.index.IndexWriter
import org.apache.lucene.index.IndexWriterConfig
import org.apache.lucene.search.SearcherFactory
import org.apache.lucene.search.SearcherManager
import org.apache.lucene.store.ByteBuffersDirectory
import org.flywaydb.core.Flyway
import org.gotson.komga.infrastructure.configuration.KomgaProperties
import org.gotson.komga.infrastructure.datasource.SqliteUdfDataSource
import org.gotson.komga.infrastructure.jooq.main.AuthenticationActivityDao
import org.gotson.komga.infrastructure.jooq.main.BookCommonDao
import org.gotson.komga.infrastructure.jooq.main.BookDao
import org.gotson.komga.infrastructure.jooq.main.BookDtoDao
import org.gotson.komga.infrastructure.jooq.main.BookMetadataAggregationDao
import org.gotson.komga.infrastructure.jooq.main.BookMetadataDao
import org.gotson.komga.infrastructure.jooq.main.BookProjectionDao
import org.gotson.komga.infrastructure.jooq.main.ClientSettingsDtoDao
import org.gotson.komga.infrastructure.jooq.main.HistoricalEventDao
import org.gotson.komga.infrastructure.jooq.main.HistoricalEventDtoDao
import org.gotson.komga.infrastructure.jooq.main.KoboDtoDao
import org.gotson.komga.infrastructure.jooq.main.KomgaUserDao
import org.gotson.komga.infrastructure.jooq.main.LibraryDao
import org.gotson.komga.infrastructure.jooq.main.MediaDao
import org.gotson.komga.infrastructure.jooq.main.PageHashDao
import org.gotson.komga.infrastructure.jooq.main.ReadListDao
import org.gotson.komga.infrastructure.jooq.main.ReadListRequestDao
import org.gotson.komga.infrastructure.jooq.main.ReadProgressDao
import org.gotson.komga.infrastructure.jooq.main.ReadProgressDtoDao
import org.gotson.komga.infrastructure.jooq.main.ReferentialDao
import org.gotson.komga.infrastructure.jooq.main.SeriesCollectionDao
import org.gotson.komga.infrastructure.jooq.main.SeriesDao
import org.gotson.komga.infrastructure.jooq.main.SeriesDtoDao
import org.gotson.komga.infrastructure.jooq.main.SeriesMetadataDao
import org.gotson.komga.infrastructure.jooq.main.ServerSettingsDao
import org.gotson.komga.infrastructure.jooq.main.SidecarDao
import org.gotson.komga.infrastructure.jooq.main.SyncPointDao
import org.gotson.komga.infrastructure.jooq.main.ThumbnailBookDao
import org.gotson.komga.infrastructure.jooq.main.ThumbnailReadListDao
import org.gotson.komga.infrastructure.jooq.main.ThumbnailSeriesCollectionDao
import org.gotson.komga.infrastructure.jooq.main.ThumbnailSeriesDao
import org.gotson.komga.infrastructure.jooq.tasks.TasksDao
import org.gotson.komga.infrastructure.search.LuceneHelper
import org.gotson.komga.infrastructure.search.LuceneSyncCommitter
import org.gotson.komga.infrastructure.search.MultiLingualAnalyzer
import org.gotson.komga.infrastructure.search.MultiLingualNGramAnalyzer
import org.jooq.DSLContext
import org.jooq.SQLDialect
import org.jooq.impl.DataSourceConnectionProvider
import org.jooq.impl.DefaultConfiguration
import org.jooq.impl.DefaultDSLContext
import org.jooq.impl.DefaultExecuteListenerProvider
import org.springframework.boot.autoconfigure.jooq.ExceptionTranslatorExecuteListener
import org.springframework.http.converter.json.Jackson2ObjectMapperBuilder
import org.springframework.jdbc.datasource.SingleConnectionDataSource
import org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy
import org.sqlite.SQLiteDataSource
import java.sql.Connection
import javax.sql.DataSource

/**
 * In-memory Komga databases for the oracle tests, without Spring. Mirrored by test/unit/db.ts in KomgaJS.
 *
 * - main database: [SqliteUdfDataSource] (REGEXP, UDF_STRIP_ACCENTS, unicode collations) on `:memory:`, foreign keys
 *   enforced like `DataSourcesConfiguration`, migrated by Flyway exactly like Spring Boot does for Komga
 *   (`classpath:db/migration/sqlite`, mixed, default placeholders of application.yml)
 * - tasks database (lazy): plain [SQLiteDataSource], migrated from `classpath:tasks/migration/sqlite`
 * - [dsl] / [tasksDsl]: jOOQ contexts built like `KomgaJooqConfiguration` (SQLITE dialect,
 *   TransactionAwareDataSourceProxy, Spring Boot's exception translator listener). The same context is used for
 *   the RW and RO roles (a single connection, like Komga with an in-memory database).
 * - every DAO of `infrastructure/jooq` (lazy properties, same names in TypeScript), with the default
 *   `batchChunkSize`, Spring Boot's Jackson [mapper] and an in-memory [lucene] index.
 *
 * `@Transactional` is not applied (no Spring proxy), on both sides: statements are executed one by one.
 * The cases of one test class share its database and run in declaration order, so the state is reproducible.
 * Ids and "now" dates generated by Komga are neutralised with [OracleTest.stable].
 */
class OracleDb : AutoCloseable {
  private fun openConnection(ds: SQLiteDataSource): SingleConnectionDataSource {
    ds.url = "jdbc:sqlite::memory:"
    ds.setEnforceForeignKeys(true)
    ds.setGetGeneratedKeys(false)
    return SingleConnectionDataSource(ds.connection, true)
  }

  private fun dslContext(dataSource: DataSource): DSLContext =
    DefaultDSLContext(
      DefaultConfiguration().also {
        it.set(SQLDialect.SQLITE)
        it.set(DataSourceConnectionProvider(TransactionAwareDataSourceProxy(dataSource)))
        it.set(DefaultExecuteListenerProvider(ExceptionTranslatorExecuteListener.DEFAULT))
      },
    )

  val properties = KomgaProperties()

  val dataSource: SingleConnectionDataSource =
    openConnection(SqliteUdfDataSource()).also {
      Flyway
        .configure()
        .dataSource(it)
        .locations("classpath:db/migration/sqlite")
        .mixed(true)
        .placeholders(placeholders)
        .load()
        .migrate()
    }

  val dsl: DSLContext = dslContext(dataSource)

  private val tasksDataSourceLazy =
    lazy {
      openConnection(SQLiteDataSource()).also {
        Flyway
          .configure()
          .dataSource(it)
          .locations("classpath:tasks/migration/sqlite")
          .load()
          .migrate()
      }
    }
  val tasksDataSource: SingleConnectionDataSource by tasksDataSourceLazy

  val tasksDsl: DSLContext by lazy { dslContext(tasksDataSource) }

  val batchSize: Int = properties.database.batchChunkSize

  /** Spring Boot's ObjectMapper (JacksonAutoConfiguration + spring.jackson.* of application.yml) */
  val mapper: ObjectMapper by lazy {
    Jackson2ObjectMapperBuilder
      .json()
      .featuresToDisable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS)
      .featuresToEnable(
        DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES,
        MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES,
        MapperFeature.ACCEPT_CASE_INSENSITIVE_VALUES,
      ).build()
  }

  /** In-memory Lucene index (profile "test" of LuceneConfiguration), synchronous commits */
  val lucene: LuceneHelper by lazy {
    val directory = ByteBuffersDirectory()
    val indexAnalyzer =
      with(properties.lucene.indexAnalyzer) { MultiLingualNGramAnalyzer(minGram, maxGram, preserveOriginal) }
    val indexWriter = IndexWriter(directory, IndexWriterConfig(indexAnalyzer))
    val searcherManager = SearcherManager(indexWriter, SearcherFactory())
    LuceneHelper(directory, MultiLingualAnalyzer(), indexAnalyzer, indexWriter, searcherManager, LuceneSyncCommitter(indexWriter, searcherManager))
  }

  val authenticationActivityDao by lazy { AuthenticationActivityDao(dsl, dsl) }
  val bookCommonDao by lazy { BookCommonDao(dsl, dsl) }
  val bookDao by lazy { BookDao(dsl, dsl, batchSize) }
  val bookDtoDao by lazy { BookDtoDao(dsl, dsl, lucene, batchSize, bookCommonDao) }
  val bookMetadataAggregationDao by lazy { BookMetadataAggregationDao(dsl, dsl, batchSize) }
  val bookMetadataDao by lazy { BookMetadataDao(dsl, dsl, batchSize) }
  val bookProjectionDao by lazy { BookProjectionDao(dsl, dsl, batchSize) }
  val clientSettingsDtoDao by lazy { ClientSettingsDtoDao(dsl, dsl) }
  val historicalEventDao by lazy { HistoricalEventDao(dsl) }
  val historicalEventDtoDao by lazy { HistoricalEventDtoDao(dsl, dsl) }
  val koboDtoDao by lazy { KoboDtoDao(dsl, dsl, mapper) }
  val komgaUserDao by lazy { KomgaUserDao(dsl, dsl) }
  val libraryDao by lazy { LibraryDao(dsl, dsl) }
  val mediaDao by lazy { MediaDao(dsl, dsl, batchSize, mapper) }
  val pageHashDao by lazy { PageHashDao(dsl, dsl) }
  val readListDao by lazy { ReadListDao(dsl, dsl, lucene, batchSize) }
  val readListRequestDao by lazy { ReadListRequestDao(dsl, dsl) }
  val readProgressDao by lazy { ReadProgressDao(dsl, dsl, batchSize, mapper) }
  val readProgressDtoDao by lazy { ReadProgressDtoDao(dsl, dsl) }
  val referentialDao by lazy { ReferentialDao(dsl, dsl) }
  val seriesCollectionDao by lazy { SeriesCollectionDao(dsl, dsl, lucene, batchSize) }
  val seriesDao by lazy { SeriesDao(dsl, dsl, batchSize) }
  val seriesDtoDao by lazy { SeriesDtoDao(dsl, dsl, lucene, batchSize) }
  val seriesMetadataDao by lazy { SeriesMetadataDao(dsl, dsl, batchSize) }
  val serverSettingsDao by lazy { ServerSettingsDao(dsl, dsl) }
  val sidecarDao by lazy { SidecarDao(dsl, dsl, batchSize) }
  val syncPointDao by lazy { SyncPointDao(dsl, dsl, bookCommonDao) }
  val thumbnailBookDao by lazy { ThumbnailBookDao(dsl, dsl, batchSize) }
  val thumbnailReadListDao by lazy { ThumbnailReadListDao(dsl, dsl) }
  val thumbnailSeriesCollectionDao by lazy { ThumbnailSeriesCollectionDao(dsl, dsl) }
  val thumbnailSeriesDao by lazy { ThumbnailSeriesDao(dsl, dsl, batchSize) }
  val tasksDao by lazy { TasksDao(tasksDsl, tasksDsl, properties.tasksDb.batchChunkSize, mapper) }

  /** Rows of a raw SQL query on the main database (JDBC getObject values: String, Int/Long, Double, ByteArray, null) */
  fun rawQuery(sql: String): List<List<Any?>> = query(dataSource.connection, sql)

  companion object {
    private val placeholders =
      mapOf(
        "library-file-hashing" to "true",
        "library-scan-startup" to "false",
        "delete-empty-collections" to "true",
        "delete-empty-read-lists" to "true",
      )

    /** A new in-memory main database (SqliteUdfDataSource), migrated up to and including version [target] */
    fun mainConnectionAt(target: String): Connection {
      val ds =
        SqliteUdfDataSource().run {
          url = "jdbc:sqlite::memory:"
          setEnforceForeignKeys(true)
          setGetGeneratedKeys(false)
          SingleConnectionDataSource(connection, true)
        }
      Flyway
        .configure()
        .dataSource(ds)
        .locations("classpath:db/migration/sqlite")
        .mixed(true)
        .placeholders(placeholders)
        .target(target)
        .load()
        .migrate()
      return ds.connection
    }

    /** Rows of a raw SQL query (JDBC getObject values: String, Int/Long, Double, ByteArray, null) */
    fun query(
      connection: Connection,
      sql: String,
    ): List<List<Any?>> =
      connection.createStatement().use { st ->
        st.executeQuery(sql).use { rs ->
          buildList {
            while (rs.next()) add((1..rs.metaData.columnCount).map { rs.getObject(it) })
          }
        }
      }

    /** Executes SQL statements one by one */
    fun exec(
      connection: Connection,
      vararg statements: String,
    ) {
      connection.createStatement().use { st -> statements.forEach { st.executeUpdate(it) } }
    }
  }

  override fun close() {
    dataSource.destroy()
    if (tasksDataSourceLazy.isInitialized()) tasksDataSource.destroy()
  }
}
